name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # openresty
  OPENRESTY_VERSION: 1.27.1.1
  OPENRESTY_PREFIX: /usr/local/apisix-unofficial-release
  OPENRESTY_CC_OPT: -O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/apisix-unofficial-release/zlib/include -I/usr/local/apisix-unofficial-release/pcre2/include -I/usr/local/apisix-unofficial-release/openssl3/include
  OPENRESTY_LD_OPT: -Wl,-rpath,/usr/local/apisix-unofficial-release/luajit/lib:/usr/local/apisix-unofficial-release/zlib/lib:/usr/local/apisix-unofficial-release/pcre2/lib:/usr/local/apisix-unofficial-release/openssl3/lib -L/usr/local/apisix-unofficial-release/zlib/lib -L/usr/local/apisix-unofficial-release/pcre2/lib -L/usr/local/apisix-unofficial-release/openssl3/lib
  OPENRESTY_LUAJIT_XCFLAGS: '-DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT'
  # lua module
  LUA_VAR_NGINX_MODULE_VERSION: v0.5.3
  LUA_RESTY_EVENTS_MODULE_VERSION: 0.3.1
  # luarocks
  LUAROCKS_PREFIX: /usr/local/apisix-unofficial-release/luarocks
  LUAROCKS_VERSION: 3.11.1
  # apisix
  APISIX_VERSION: master

jobs:
  build:
    runs-on: ubuntu-20.04
    name: build
    steps:
      - name: Set up apt repository for openresty
        run: |
          sudo apt-get -y install --no-install-recommends wget gnupg ca-certificates lsb-release
          wget -O - https://openresty.org/package/pubkey.gpg | sudo gpg --dearmor -o /usr/share/keyrings/openresty.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/openresty.gpg] http://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list > /dev/null
          sudo apt-get update
      - name: Install openresty lib package and dev package
        run: |
          sudo apt-get -y install openresty-openssl3 openresty-openssl3-dev \
            openresty-pcre2 openresty-pcre2-dev \
            openresty-zlib openresty-zlib-dev \
            openresty-pcre openresty-pcre-dev
          sudo mkdir -p $OPENRESTY_PREFIX
          sudo chown -R $(id -u):$(id -g) $OPENRESTY_PREFIX
          sudo cp -r /usr/local/openresty/zlib $OPENRESTY_PREFIX
          sudo cp -r /usr/local/openresty/pcre $OPENRESTY_PREFIX
          sudo cp -r /usr/local/openresty/pcre2 $OPENRESTY_PREFIX
          sudo cp -r /usr/local/openresty/openssl3 $OPENRESTY_PREFIX
      - name: Download module
        run: |
          sudo chown -R $(id -u):$(id -g) /usr/local/src/
          cd /usr/local/src/
          git clone --depth=1 -b ${LUA_VAR_NGINX_MODULE_VERSION} https://github.com/api7/lua-var-nginx-module lua-var-nginx-module-${LUA_VAR_NGINX_MODULE_VERSION}
          git clone --depth=1 -b ${LUA_RESTY_EVENTS_MODULE_VERSION} https://github.com/Kong/lua-resty-events.git lua-resty-events-${LUA_RESTY_EVENTS_MODULE_VERSION}
      - name: Download openresty and build
        run: |
          wget --no-check-certificate https://openresty.org/download/openresty-$OPENRESTY_VERSION.tar.gz
          tar -zxvpf openresty-$OPENRESTY_VERSION.tar.gz -C /usr/local/src/ > /dev/null
          cd /usr/local/src/openresty-$OPENRESTY_VERSION || exit 1
          ./configure \
            --prefix="$OPENRESTY_PREFIX" \
            --with-cc-opt="$OPENRESTY_CC_OPT" \
            --with-ld-opt="$OPENRESTY_LD_OPT" \
            --with-luajit-xcflags="$OPENRESTY_LUAJIT_XCFLAGS" \
            --add-module=../lua-var-nginx-module-$LUA_VAR_NGINX_MODULE_VERSION \
            --add-module=../lua-resty-events-$LUA_RESTY_EVENTS_MODULE_VERSION \
            --with-poll_module \
            --with-pcre-jit \
            --without-http_rds_json_module \
            --without-http_rds_csv_module \
            --without-lua_rds_parser \
            --with-stream \
            --with-stream_ssl_module \
            --with-stream_ssl_preread_module \
            --with-http_v2_module \
            --with-http_v3_module \
            --without-mail_pop3_module \
            --without-mail_imap_module \
            --without-mail_smtp_module \
            --with-http_stub_status_module \
            --with-http_realip_module \
            --with-http_addition_module \
            --with-http_auth_request_module \
            --with-http_secure_link_module \
            --with-http_random_index_module \
            --with-http_gzip_static_module \
            --with-http_sub_module \
            --with-http_dav_module \
            --with-http_flv_module \
            --with-http_mp4_module \
            --with-http_slice_module \
            --with-http_gunzip_module \
            --with-threads \
            --with-compat \
            -j`nproc`
          make -j`nproc`
          make install
      - name: Build from luarocks source and install
        run: |
          wget https://github.com/luarocks/luarocks/archive/refs/tags/v$LUAROCKS_VERSION.tar.gz
          mkdir /usr/local/src/luarocks
          tar -zxvpf v$LUAROCKS_VERSION.tar.gz -C /usr/local/src/luarocks > /dev/null
          cd /usr/local/src/luarocks/luarocks-$LUAROCKS_VERSION
          ./configure --prefix=/usr/local/apisix-unofficial-release/luarocks --with-lua=/usr/local/apisix-unofficial-release/luajit/
          make
          make install
          $LUAROCKS_PREFIX/bin/luarocks config variables.OPENSSL_LIBDIR $OPENRESTY_PREFIX/openssl3/lib
          $LUAROCKS_PREFIX/bin/luarocks config variables.OPENSSL_INCDIR $OPENRESTY_PREFIX/openssl3/include
          $LUAROCKS_PREFIX/bin/luarocks config variables.PCRE_LIBDIR $OPENRESTY_PREFIX/pcre/lib/
          $LUAROCKS_PREFIX/bin/luarocks config variables.PCRE_INCDIR $OPENRESTY_PREFIX/pcre/include/
      - name: Download apisix and install
        run: |
          cd $OPENRESTY_PREFIX
          git clone --depth=1 -b ${APISIX_VERSION} https://github.com/apache/apisix.git apisix-${APISIX_VERSION}
          cd apisix-${APISIX_VERSION}
          $LUAROCKS_PREFIX/bin/luarocks install apisix-master-0.rockspec --tree deps --only-deps
      - name: Build deb package
        run: |
          mkdir -p pkg/usr/local
          mkdir -p pkg/DEBIAN
          sudo chown -R $(id -u):$(id -g) pkg
          cp -r $OPENRESTY_PREFIX pkg/usr/local
          cat << EOF > pkg/DEBIAN/control
          Package: apisix-unofficial-release
          Version: 0.1
          Maintainer: yuweizzz
          Architecture: amd64
          Description: apisix unofficial release
          EOF
          dpkg-deb -Z xz --build pkg apisix-unofficial-release_0.1_amd64.deb
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ github.ref_name }}-${{ runner.os }}-amd64
          path: ./*.deb
